### ISSUE TITLE
RR Intervals should be supported by zero-to-many values

### ISSUE THREAD

**Issue by edorphy** [codeinversion/sensors-swift#6]
Heart Rate Measurement Value characteristic supports zero-to-many RR intervals. This code expects zero or one value to be present.

https://www.bluetooth.com/xml-viewer/?src=https://www.bluetooth.com/wp-content/uploads/Sitecore-Media-Library/Gatt/Xml/Characteristics/org.bluetooth.characteristic.heart_rate_measurement.xml#tree0:0,6,2|0,6,3|0,6,4;

The Polar HR7 (and presumably HR10) supports multiple RR-Interval values

**Comment by netizen01** [comment]
More detail here:
https://www.bluetooth.org/docman/handlers/downloaddoc.ashx?doc_id=239866

**Comment by edorphy** [comment]
Why was this closed? Section 3.1 of the document you linked describes that the measurement characteristic may have up to 8 rr-intervals.

**Comment by netizen01** [comment]
Oh! Sorry - I didn’t link the commit.
The update is on master.
