### ISSUE TITLE
WatchOS Support

### ISSUE THREAD

**Issue by We-Are-Empire** [codeinversion/sensors-swift#8]
Hi there, great work. Just wondering if there's anything preventing WatchOS support? Or just a matter of updating the podspec?

Cheers!

**Comment by netizen01** [comment]
Not sure. I haven't checked on the latest watchOS SDKs to see if they've added the full iOS BLE stack that this is built on. I'll check.

**Comment by netizen01** [comment]
Looks like it should work. I've added watchOS as a supported platform in the Package.swift file (SPM).
Swift Package Manager is the preferred way to import this library - I don't anticipate supporting CocoaPods going forward.

**Comment by We-Are-Empire** [comment]
Amazing, thank you
